/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Hp
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    File file;
    Color backgroundColor;
    Color foregroundColor;
    int firstArgument;
    
    public DashBoard() {
        setLocationRelativeTo(null);
        backgroundColor = new Color(255,255,255);
        foregroundColor = new Color(204, 0, 51);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSideBar = new javax.swing.JPanel();
        btnBarChart = new javax.swing.JButton();
        btnAreaChart = new javax.swing.JButton();
        btnLineChart = new javax.swing.JButton();
        btnSelectFile = new javax.swing.JButton();
        btnBarChart3D = new javax.swing.JButton();
        lblChartName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPieChart = new javax.swing.JButton();
        btnPieChart3d = new javax.swing.JButton();
        txtXAxix = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtYAxisName = new javax.swing.JTextField();
        btnForegroundColor = new javax.swing.JButton();
        btnBackgroundColor = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();
        pnlBarChart = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSideBar.setBackground(new java.awt.Color(0, 135, 135));

        btnBarChart.setBackground(new java.awt.Color(0, 204, 204));
        btnBarChart.setText("Bar Chart");
        btnBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarChartActionPerformed(evt);
            }
        });

        btnAreaChart.setBackground(new java.awt.Color(0, 204, 204));
        btnAreaChart.setText("AreaChart");
        btnAreaChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaChartActionPerformed(evt);
            }
        });

        btnLineChart.setBackground(new java.awt.Color(0, 204, 204));
        btnLineChart.setText("Line Chart");
        btnLineChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineChartActionPerformed(evt);
            }
        });

        btnSelectFile.setBackground(new java.awt.Color(0, 204, 204));
        btnSelectFile.setText("Select A File");
        btnSelectFile.setToolTipText("Browse For A File");
        btnSelectFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSelectFile.setBorderPainted(false);
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        btnBarChart3D.setBackground(new java.awt.Color(0, 204, 204));
        btnBarChart3D.setText("Bar Chart 3D");
        btnBarChart3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarChart3DActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter The Title For Your Chart ");

        btnPieChart.setBackground(new java.awt.Color(0, 204, 204));
        btnPieChart.setText("Pie Chart");
        btnPieChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieChartActionPerformed(evt);
            }
        });

        btnPieChart3d.setBackground(new java.awt.Color(0, 204, 204));
        btnPieChart3d.setText("Pie Chart 3D");
        btnPieChart3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieChart3dActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter X-Axis Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Y-Axis Name");

        btnForegroundColor.setBackground(new java.awt.Color(51, 255, 51));
        btnForegroundColor.setText("Foreground Color");
        btnForegroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForegroundColorActionPerformed(evt);
            }
        });

        btnBackgroundColor.setBackground(new java.awt.Color(51, 255, 51));
        btnBackgroundColor.setForeground(new java.awt.Color(0, 0, 0));
        btnBackgroundColor.setText("Background Color");
        btnBackgroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackgroundColorActionPerformed(evt);
            }
        });

        lblFileName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFileName.setText("File Name: ");

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPieChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAreaChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLineChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarChart3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPieChart3d, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSideBarLayout.createSequentialGroup()
                        .addComponent(btnForegroundColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSideBarLayout.createSequentialGroup()
                        .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtYAxisName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblChartName)
                                    .addComponent(txtXAxix))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(lblFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChartName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXAxix, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtYAxisName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarChart3D, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAreaChart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPieChart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPieChart3d, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForegroundColor)
                    .addComponent(btnBackgroundColor))
                .addGap(18, 18, 18))
        );

        pnlBarChart.setVisible(true);

        javax.swing.GroupLayout pnlBarChartLayout = new javax.swing.GroupLayout(pnlBarChart.getContentPane());
        pnlBarChart.getContentPane().setLayout(pnlBarChartLayout);
        pnlBarChartLayout.setHorizontalGroup(
            pnlBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        pnlBarChartLayout.setVerticalGroup(
            pnlBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBarChart)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBarChart, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarChartActionPerformed
        // TODO add your handling code here:
        
        DefaultCategoryDataset set = new DefaultCategoryDataset();
        
        
//        JFileChooser chooser = new JFileChooser();
//        
//        chooser.showOpenDialog(null);
//        
//        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr;
            
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                firstArgument = Integer.parseInt(arr[1]);
                set.addValue(firstArgument, lblChartName.getText(), arr[0]); 
            }
            
            JFreeChart chart = ChartFactory.createBarChart(lblChartName.getText(), txtXAxix.getText(), txtYAxisName.getText(), set);
            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(backgroundColor);
            
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            Color clr3 = new Color(204, 0, 51);
            renderer.setSeriesPaint(0, foregroundColor);
            
            
            
            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
           
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnBarChartActionPerformed

    private void btnLineChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineChartActionPerformed
        // TODO add your handling code here:
        

        DefaultCategoryDataset set = new DefaultCategoryDataset();
        
//        JFileChooser chooser = new JFileChooser();
//        
//        chooser.showOpenDialog(null);
//        
//        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr;
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                int firstArgument = Integer.parseInt(arr[1]);
                set.addValue(firstArgument, lblChartName.getText(), arr[0]); 
            }
            
            JFreeChart chart = ChartFactory.createLineChart(lblChartName.getText(), txtXAxix.getText(), txtYAxisName.getText(), set);
            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(backgroundColor);
            
            plot.getRenderer().setSeriesStroke(0, new BasicStroke(3.0f));
            
            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLineChartActionPerformed

    private void btnAreaChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaChartActionPerformed
        // TODO add your handling code here:
        
        DefaultCategoryDataset set = new DefaultCategoryDataset();
        
//        JFileChooser chooser = new JFileChooser();
//        
//        chooser.showOpenDialog(null);
//        
//        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr = new String[2];
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                int firstArgument = Integer.parseInt(arr[1]);
                set.addValue(firstArgument, lblChartName.getText(), arr[0]); 
            }
            
            JFreeChart chart = ChartFactory.createAreaChart(lblChartName.getText(), txtXAxix.getText(), txtYAxisName.getText(), set);
            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(backgroundColor);
            
            
            
            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAreaChartActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        file = chooser.getSelectedFile();
        String name = file.getName();
        
        
        lblFileName.setText("File Name: " + name);
        
        
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnBarChart3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarChart3DActionPerformed
        // TODO add your handling code here:
        
        DefaultCategoryDataset set = new DefaultCategoryDataset();
        
//        JFileChooser chooser = new JFileChooser();
//        
//        chooser.showOpenDialog(null);
//        
//        File file = chooser.getSelectedFile();
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr;
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                int firstArgument = Integer.parseInt(arr[1]);
                set.addValue(firstArgument, lblChartName.getText(), arr[0]); 
            }
            
            JFreeChart chart = ChartFactory.createBarChart3D(lblChartName.getText(), txtXAxix.getText(), txtYAxisName.getText(), set);
            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(backgroundColor);
            
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            Color clr3 = new Color(204, 0, 51);
            renderer.setSeriesPaint(0, foregroundColor);
            
            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex)
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBarChart3DActionPerformed

    private void btnPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieChartActionPerformed
        // TODO add your handling code here:
        
        DefaultPieDataset dataset = new DefaultPieDataset();
        
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr;
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                int firstArgument = Integer.parseInt(arr[1]);
                dataset.setValue(arr[0], firstArgument);
            }
            
            JFreeChart chart = ChartFactory.createPieChart(lblChartName.getText(), dataset, true, true, false);

            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPieChartActionPerformed

    private void btnPieChart3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieChart3dActionPerformed
        // TODO add your handling code here:
        
        DefaultPieDataset dataset = new DefaultPieDataset();
        
        String path = file.getAbsolutePath();
        try 
        {
            BufferedReader reader = new BufferedReader(new FileReader(path));
            
            String line;
            String[] arr;
            while((line = reader.readLine()) != null)
            {
                arr = line.split(",");
                int firstArgument = Integer.parseInt(arr[1]);
                dataset.setValue(arr[0], firstArgument);
            }
            
            JFreeChart chart = ChartFactory.createPieChart3D(lblChartName.getText(), dataset, true, true, false);
            
            ChartPanel panel = new ChartPanel(chart);
            pnlBarChart.setContentPane(panel);
            
            pnlBarChart.setVisible(true);
            
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPieChart3dActionPerformed

    private void btnForegroundColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForegroundColorActionPerformed
        // TODO add your handling code here:
        JColorChooser chooser = new JColorChooser();
        
        foregroundColor = JColorChooser.showDialog(this, "Select a Color", foregroundColor);
    }//GEN-LAST:event_btnForegroundColorActionPerformed

    private void btnBackgroundColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackgroundColorActionPerformed
        // TODO add your handling code here:
        JColorChooser chooser = new JColorChooser();
        backgroundColor = JColorChooser.showDialog(this, "Select A Color", backgroundColor);
        
    }//GEN-LAST:event_btnBackgroundColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaChart;
    private javax.swing.JButton btnBackgroundColor;
    private javax.swing.JButton btnBarChart;
    private javax.swing.JButton btnBarChart3D;
    private javax.swing.JButton btnForegroundColor;
    private javax.swing.JButton btnLineChart;
    private javax.swing.JButton btnPieChart;
    private javax.swing.JButton btnPieChart3d;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lblChartName;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JInternalFrame pnlBarChart;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JTextField txtXAxix;
    private javax.swing.JTextField txtYAxisName;
    // End of variables declaration//GEN-END:variables
}
